### PR TITLE
First pass

### PR DESCRIPTION
**Pull request by mixmix**
So far have only added **opinionated** key derivation test vector.
See README for spec about how the test vector was generated, as it takes in some details of Go implementation but some things are different too (primarily - using snake_case)

I've added a package.json file to make this easier to link / import into js tests.

### CODE REVIEW

**Comment by dominictarr** [comment]
The strings in the go code use "flatcase" which is bad, because the word separation is not machine readable which in some cases produces ambiguity.

**Comment by keks** [comment]
What is flat-case? The info fields are length-prefixed to avoid ambiguity, or am I missing something?

https://github.com/cryptoscope/ssb/blob/8bd29470a23c73434e6c64d48beb134faf048b70/keys/key.go#L29:L39

(I don't object to use a different encoding, I'll try to take a look this weekend)

**Comment by mixmix** [comment]
@keks cases I know:

style name | example
---|---
snake case | `external_nonce`
kebab case | `external-nonce`
camel case | `externalNonce`
capital case | `ExternalNonce`
flat case  | `externalnonce`

What @dominictarr was trying to convey was that flat case can cause problems if we want to parse the variable, because it's unclear where the word-break lands. was it "extern alnonce"?

----

not sure what you meant "the fields are length-prefixed". Tried looking at code you posted but it didn't clarify for me (still learning to read go)

**Comment by mixmix** [comment]
merging this because it's basically our working master branch

**Pull request merged**
